version: '3.8'

services:
  dispatch-monitoring:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos
      - ./models:/app/models
      - ./feedback:/app/feedback
      - ./templates:/app/templates
    restart: unless-stopped
