# docker-compose.yml
version: '3.8'

services:
  dispatch-monitor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos
      - ./feedback:/app/feedback
      - ./models:/app/models
      - ./dataset:/app/dataset
    environment:
      - FLASK_ENV=production
    restart: unless-stopped